const mongoose = require('mongoose');
const Tour = require('../models/Tour');

mongoose.connect('mongodb://localhost:27017/terravue', {
    useNewUrlParser: true,
    useUnifiedTopology: true,
});

const tours = [
    {
        title: "Cappadocia",
        country: "Turkey",
        days: 5,
        price: 92,
        oldPrice: 98,
        image: "/images/cappadocia.jpg",
        currency: "USD",
        description: "Cappadocia offers a magical experience with its hot air balloons and unique rock formations.",
    },
    {
        title: "Santorini",
        country: "Greece",
        days: 6,
        price: 120,
        oldPrice: 135,
        image: "/images/santorini.jpg",
        currency: "USD",
        description: "Santorini offers stunning views, crystal-clear waters, and an unforgettable sunset experience.",
    },
    {
        title: "Bali",
        country: "Indonesia",
        days: 7,
        price: 150,
        oldPrice: 160,
        image: "/images/bali.jpg",
        currency: "USD",
        description: "Bali is known for its beautiful beaches, lush landscapes, and vibrant culture.",
    },
    {
        title: "Phuket",
        country: "Thailand",
        days: 5,
        price: 110,
        oldPrice: 115,
        image: "/images/phuket.jpg",
        currency: "USD",
        description: "The Kophi-Thailand Tour is a unique experience that combines the natural beauty of Thailand with a love for coffee.",
    },
    {
        title: "Maldives",
        country: "Maldives",
        days: 6,
        price: 180,
        oldPrice: 200,
        image: "/images/maldives1.jpg",
        currency: "USD",
        description: "The Maldives is a paradise with turquoise waters, white sandy beaches, and luxurious resorts.",
    },
    {
        title: "Paris",
        country: "France",
        days: 4,
        price: 130,
        oldPrice: 140,
        image: "/images/paris.jpg",
        currency: "USD",
        description: "Paris is a romantic city known for its art, culture, and iconic landmarks like the Eiffel Tower.",
    },
    {
        title: "Kyoto",
        country: "Japan",
        days: 5,
        price: 140,
        oldPrice: 150,
        image: "/images/kyoto.jpg",
        currency: "USD",
        description: "Kyoto is famous for its traditional temples, beautiful gardens, and stunning cherry blossoms.",
    },
    {
        title: "Dubai",
        country: "UAE",
        days: 3,
        price: 100,
        oldPrice: 110,
        image: "/images/dubai.jpg",
        currency: "USD",
        description: "Dubai is a futuristic city known for its skyscrapers, luxury shopping, and vibrant nightlife.",
    },
    {
        title: "Rome",
        country: "Italy",
        days: 6,
        price: 145,
        oldPrice: 155,
        image: "/images/rome.jpg",
        currency: "USD",
        description: "Rome is steeped in history, with iconic landmarks such as the Colosseum and the Vatican.",
    },
    {
        title: "Barcelona",
        country: "Spain",
        days: 5,
        price: 135,
        oldPrice: 145,
        image: "/images/barcelona.jpg",
        currency: "USD",
        description: "Barcelona is a dynamic city known for its architecture, culture, and lively beaches.",
    },
    {
        title: "New York",
        country: "USA",
        days: 4,
        price: 170,
        oldPrice: 180,
        image: "/images/newyork.jpg",
        currency: "USD",
        description: "New York is a bustling metropolis with endless things to see, from Broadway to Central Park.",
    },
    {
        title: "Sydney",
        country: "Australia",
        days: 7,
        price: 160,
        oldPrice: 175,
        image: "/images/sydney.jpg",
        currency: "USD",
        description: "Sydney is home to iconic landmarks like the Opera House and beautiful beaches.",
    },
    {
        title: "Goa",
        country: "India",
        days: 5,
        price: 6000,
        oldPrice: 7000,
        image: "/images/goa.jpg",
        currency: "INR",
        description: "Goa is a tropical paradise known for its beautiful beaches and vibrant nightlife.",
    },
    {
        title: "Kerala",
        country: "India",
        days: 6,
        price: 5500,
        oldPrice: 6000,
        image: "/images/munnar.jpg",
        currency: "INR",
        description: "Kerala, often called 'God's Own Country,' is known for its tranquil backwaters, lush landscapes, and rich culture.",
    },
    {
        title: "Rajasthan",
        country: "India",
        days: 7,
        price: 8000,
        oldPrice: 8500,
        image: "/images/rajasthan.jpg",
        currency: "INR",
        description: "Rajasthan is a land of palaces, forts, and vibrant culture, offering a unique glimpse into India's royal heritage.",
    },
];

Tour.insertMany(tours)
    .then(() => {
        console.log('✅ Tours added!');
        mongoose.disconnect();
    })
    .catch((err) => {
        console.error('❌ Error inserting tours:', err);
    });
